---
- hosts: nas
  become: False
  vars: 
    current_version: "{{ version  }}" 
    current_build: "{{ build  }}"
  tasks:
    - name: Copying files to NAS
      copy:
        src: ./doc/main.-{{ current_version  }}-{{ current_build  }}.pdf
        dest: /home/staffan/Downloads
        owner: staffan
        group: staffan        
        mode: 0644
